version: '3.8'
services:
  db:
    image: mysql:5.7
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: myapp_development
    ports:
      - "3307:3307"  # Corrected port mapping

  web:
    build: .
    command: bundle exec rails s -b '0.0.0.0' -p 3001
    volumes:
      - ".:/usr/src/app"
    ports:
      - "3001:3001"
    depends_on:
      - db
